version: '3.8'

services:
  onepiece-cards:
    build: .
    container_name: onepiece-cards
    ports:
      - "80:8080"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8080
    restart: unless-stopped
    networks:
      - card-network

networks:
  card-network:
    driver: bridge 