package com.onepiece.cardmanager.config;

import com.onepiece.cardmanager.model.Card;
import com.onepiece.cardmanager.repository.CardRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

@Component
@Order(2)
public class OP02Initializer extends BaseInitializer {

    private final CardRepository cardRepository;

    @Autowired
    public OP02Initializer(CardRepository cardRepository) {
        this.cardRepository = cardRepository;
    }

    @Override
    protected void initialize(String... args) throws Exception {
        // Only initialize if we have no OP02 cards
        if (cardRepository.countBySetAndCardNumberStartingWith("OP02", "OP02") > 0) {
            System.out.println("OP02 cards already exist, skipping initialization");
            return;
        }

        System.out.println("Initializing OP02 cards...");
        
        // Red Cards
        Card edwardNewgateLeader = new Card();
        edwardNewgateLeader.setCardNumber("OP02-001");
        edwardNewgateLeader.setName("Edward Newgate");
        edwardNewgateLeader.setCardType("Leader");
        edwardNewgateLeader.setColor("Red");
        edwardNewgateLeader.setPower(6000);
        edwardNewgateLeader.setLife(6);
        edwardNewgateLeader.setAttribute("Special");
        edwardNewgateLeader.setAffiliations("The Four Emperors/Whitebeard Pirates");
        edwardNewgateLeader.setEffect("End of Your Turn Add 1 card from the top of your Life Area to your hand.");
        edwardNewgateLeader.setImagePath("/images/cards/OP02/OP02-001.png");
        cardRepository.save(edwardNewgateLeader);
        
        Card monkeyDGarpLeader = new Card();
        monkeyDGarpLeader.setCardNumber("OP02-002");
        monkeyDGarpLeader.setName("Monkey D. Garp");
        monkeyDGarpLeader.setCardType("Leader");
        monkeyDGarpLeader.setColor("Black"); // Assuming Black as primary
        monkeyDGarpLeader.setPower(5000);
        monkeyDGarpLeader.setLife(4);
        monkeyDGarpLeader.setAttribute("Strike");
        monkeyDGarpLeader.setAffiliations("Navy");
        monkeyDGarpLeader.setEffect("Your Turn When you attach DON!! to this Leader or 1 of your Characters, give up to 1 of your opponent's 7 cost or lower Characters -1 to their cost during this turn.");
        monkeyDGarpLeader.setImagePath("/images/cards/OP02/OP02-002.png");
        cardRepository.save(monkeyDGarpLeader);

        Card atmos = new Card();
        atmos.setCardNumber("OP02-003");
        atmos.setName("Atmos");
        atmos.setCardType("Character");
        atmos.setColor("Red");
        atmos.setCost(4);
        atmos.setPower(6000);
        atmos.setCounter(1000);
        atmos.setAttribute("Slash");
        atmos.setAffiliations("Whitebeard Pirates");
        atmos.setImagePath("/images/cards/OP02/OP02-003.png");
        cardRepository.save(atmos);

        Card edwardNewgate = new Card();
        edwardNewgate.setCardNumber("OP02-004");
        edwardNewgate.setName("Edward Newgate");
        edwardNewgate.setCardType("Character");
        edwardNewgate.setColor("Red");
        edwardNewgate.setCost(9);
        edwardNewgate.setPower(10000);
        edwardNewgate.setAttribute("Special");
        edwardNewgate.setAffiliations("The Four Emperors/Whitebeard Pirates");
        edwardNewgate.setEffect("On Play Up to 1 of your Leader gains +2000 until the start of your next turn. Then, you cannot add cards from your Life area to your hand by your effects during this turn.\\nDON!!x2 When Attacking K.O. up to 1 of your opponent's Characters with 3000 or less Power.");
        edwardNewgate.setImagePath("/images/cards/OP02/OP02-004.png");
        cardRepository.save(edwardNewgate);

        Card curlyDadan = new Card();
        curlyDadan.setCardNumber("OP02-005");
        curlyDadan.setName("Curly Dadan");
        curlyDadan.setCardType("Character");
        curlyDadan.setColor("Red");
        curlyDadan.setCost(2);
        curlyDadan.setPower(3000);
        curlyDadan.setCounter(1000);
        curlyDadan.setAttribute("Slash");
        curlyDadan.setAffiliations("Mountain Bandit");
        curlyDadan.setEffect("On Play Look at 5 cards from the top of your deck; reveal up to 1 red Character card with a cost of 1 or less and add it to your hand. Then, place the rest at the bottom of your deck in any order.");
        curlyDadan.setImagePath("/images/cards/OP02/OP02-005.png");
        cardRepository.save(curlyDadan);

        Card kingdew = new Card();
        kingdew.setCardNumber("OP02-006");
        kingdew.setName("Kingdew");
        kingdew.setCardType("Character");
        kingdew.setColor("Red");
        kingdew.setCost(5);
        kingdew.setPower(7000);
        kingdew.setCounter(1000);
        kingdew.setAttribute("Strike");
        kingdew.setAffiliations("Whitebeard Pirates");
        kingdew.setImagePath("/images/cards/OP02/OP02-006.png");
        cardRepository.save(kingdew);

        Card thatch = new Card();
        thatch.setCardNumber("OP02-007");
        thatch.setName("Thatch");
        thatch.setCardType("Character");
        thatch.setColor("Red");
        thatch.setCost(6);
        thatch.setPower(8000);
        thatch.setCounter(1000);
        thatch.setAttribute("Wisdom");
        thatch.setAffiliations("Whitebeard Pirates");
        thatch.setImagePath("/images/cards/OP02/OP02-007.png");
        cardRepository.save(thatch);

        Card jozu = new Card();
        jozu.setCardNumber("OP02-008");
        jozu.setName("Jozu");
        jozu.setCardType("Character");
        jozu.setColor("Red");
        jozu.setCost(4);
        jozu.setPower(4000);
        jozu.setCounter(2000);
        jozu.setAttribute("Strike");
        jozu.setAffiliations("Whitebeard Pirates");
        jozu.setEffect("DON!!x1 If you have 2 or less Life cards and your Leader has (Whitebeard Pirates) in its type, this Character gains Rush (This card can attack on the turn in which it is played.)");
        jozu.setImagePath("/images/cards/OP02/OP02-008.png");
        cardRepository.save(jozu);

        Card squard = new Card();
        squard.setCardNumber("OP02-009");
        squard.setName("Squard");
        squard.setCardType("Character");
        squard.setColor("Red");
        squard.setCost(3);
        squard.setPower(5000);
        squard.setAttribute("Slash");
        squard.setAffiliations("Whitebeard Pirates Subordinates");
        squard.setEffect("On Play If your Leader has the {Whitebeard Pirates} type, give up to 1 of your opponent's Characters -4000 Power during this turn, then add the top card from your Life area to your hand.");
        squard.setImagePath("/images/cards/OP02/OP02-009.png");
        cardRepository.save(squard);

        Card dogura = new Card();
        dogura.setCardNumber("OP02-010");
        dogura.setName("Dogura");
        dogura.setCardType("Character");
        dogura.setColor("Red");
        dogura.setCost(1);
        dogura.setPower(2000);
        dogura.setCounter(1000);
        dogura.setAttribute("Slash");
        dogura.setAffiliations("Mountain Bandits");
        dogura.setEffect("Activate: Main You may rest this Character: Play up to 1 red Character other than [Dogura] with a cost of 1 from your hand.");
        dogura.setImagePath("/images/cards/OP02/OP02-010.png");
        cardRepository.save(dogura);

        Card vista = new Card();
        vista.setCardNumber("OP02-011");
        vista.setName("Vista");
        vista.setCardType("Character");
        vista.setColor("Red");
        vista.setCost(3);
        vista.setPower(3000);
        vista.setCounter(1000);
        vista.setAttribute("Slash");
        vista.setAffiliations("Whitebeard Pirates");
        vista.setEffect("On Play K.O up to 1 of your opponent's Characters with 3000 power or less.");
        vista.setImagePath("/images/cards/OP02/OP02-011.png");
        cardRepository.save(vista);

        Card blenheim = new Card();
        blenheim.setCardNumber("OP02-012");
        blenheim.setName("Blenheim");
        blenheim.setCardType("Character");
        blenheim.setColor("Red");
        blenheim.setCost(2);
        blenheim.setPower(3000);
        blenheim.setCounter(1000);
        blenheim.setAttribute("Slash");
        blenheim.setAffiliations("Whitebeard Pirates");
        blenheim.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        blenheim.setImagePath("/images/cards/OP02/OP02-012.png");
        cardRepository.save(blenheim);

        Card portgasDAce = new Card();
        portgasDAce.setCardNumber("OP02-013");
        portgasDAce.setName("Portgas. D. Ace");
        portgasDAce.setCardType("Character");
        portgasDAce.setColor("Red");
        portgasDAce.setCost(7);
        portgasDAce.setPower(7000);
        portgasDAce.setAttribute("Special");
        portgasDAce.setAffiliations("Whitebeard Pirates");
        portgasDAce.setEffect("On Play Give up to 2 of your opponent's Characters -3000 Power during this turn. Then, if your Leader has [Whitebeard Pirates] in its types, this Character gains Rush during this turn.");
        portgasDAce.setImagePath("/images/cards/OP02/OP02-013.png");
        cardRepository.save(portgasDAce);

        Card whiteyBay = new Card();
        whiteyBay.setCardNumber("OP02-014");
        whiteyBay.setName("Whitey Bay");
        whiteyBay.setCardType("Character");
        whiteyBay.setColor("Red");
        whiteyBay.setCost(1);
        whiteyBay.setPower(2000);
        whiteyBay.setCounter(1000);
        whiteyBay.setAttribute("Slash");
        whiteyBay.setAffiliations("White Beard Pirates Subordinates");
        whiteyBay.setEffect("DON!!x1 This Character can also attack your opponent's active Characters.");
        whiteyBay.setImagePath("/images/cards/OP02/OP02-014.png");
        cardRepository.save(whiteyBay);

        Card makino = new Card();
        makino.setCardNumber("OP02-015");
        makino.setName("Makino");
        makino.setCardType("Character");
        makino.setColor("Red");
        makino.setCost(1);
        makino.setPower(0);
        makino.setCounter(2000);
        makino.setAttribute("Wisdom");
        makino.setAffiliations("Windmill Village");
        makino.setEffect("Activate: Main You may rest this Character: Up to 1 of your red Characters with a cost of 1 gains +3000 power during this turn.");
        makino.setImagePath("/images/cards/OP02/OP02-015.png");
        cardRepository.save(makino);

        Card magra = new Card();
        magra.setCardNumber("OP02-016");
        magra.setName("Magra");
        magra.setCardType("Character");
        magra.setColor("Red");
        magra.setCost(1);
        magra.setPower(2000);
        magra.setCounter(1000);
        magra.setAttribute("Slash");
        magra.setAffiliations("Mountain Bandit");
        magra.setEffect("On Play Up to 1 of your Red Characters with a costs of 1 gains +3000 Power during this turn.");
        magra.setImagePath("/images/cards/OP02/OP02-016.png");
        cardRepository.save(magra);

        Card maskedDeuce = new Card();
        maskedDeuce.setCardNumber("OP02-017");
        maskedDeuce.setName("Masked Deuce");
        maskedDeuce.setCardType("Character");
        maskedDeuce.setColor("Red");
        maskedDeuce.setCost(2);
        maskedDeuce.setPower(3000);
        maskedDeuce.setCounter(2000);
        maskedDeuce.setAttribute("Wisdom");
        maskedDeuce.setAffiliations("Spade Pirates");
        maskedDeuce.setEffect("DON!!x2 When attacking K.O. up to 1 of your opponent's Characters with 2000 power or less.");
        maskedDeuce.setImagePath("/images/cards/OP02/OP02-017.png");
        cardRepository.save(maskedDeuce);

        Card marcoOP02 = new Card();
        marcoOP02.setCardNumber("OP02-018");
        marcoOP02.setName("Marco");
        marcoOP02.setCardType("Character");
        marcoOP02.setColor("Red");
        marcoOP02.setCost(4);
        marcoOP02.setPower(5000);
        marcoOP02.setCounter(1000);
        marcoOP02.setAttribute("Special");
        marcoOP02.setAffiliations("Whitebeard Pirates");
        marcoOP02.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\\nOn K.O. You may trash 1 card from your hand with {Whitebeard Pirates} in its type: If you have 2 or less Life cards, play this Character card from your Trash rested.");
        marcoOP02.setImagePath("/images/cards/OP02/OP02-018.png");
        cardRepository.save(marcoOP02);

        Card rakuyo = new Card();
        rakuyo.setCardNumber("OP02-019");
        rakuyo.setName("Rakuyo");
        rakuyo.setCardType("Character");
        rakuyo.setColor("Red");
        rakuyo.setCost(3);
        rakuyo.setPower(4000);
        rakuyo.setCounter(1000);
        rakuyo.setAttribute("Strike");
        rakuyo.setAffiliations("Whitebeard Pirates");
        rakuyo.setEffect("DON!!x1 Your Turn All of your Characters with {Whitebeard Pirates} in their types gain +1000 Power.");
        rakuyo.setImagePath("/images/cards/OP02/OP02-019.png");
        cardRepository.save(rakuyo);

        Card littleOarsJr = new Card();
        littleOarsJr.setCardNumber("OP02-020");
        littleOarsJr.setName("Little Oars Jr.");
        littleOarsJr.setCardType("Character");
        littleOarsJr.setColor("Red");
        littleOarsJr.setCost(7);
        littleOarsJr.setPower(9000);
        littleOarsJr.setCounter(1000);
        littleOarsJr.setAttribute("Strike");
        littleOarsJr.setAffiliations("Giant/Whitebeard Pirates Subordinates");
        littleOarsJr.setImagePath("/images/cards/OP02/OP02-020.png");
        cardRepository.save(littleOarsJr);
        
        // Red Events & Stages
        Card seaquake = new Card();
        seaquake.setCardNumber("OP02-021");
        seaquake.setName("Seaquake");
        seaquake.setCardType("Event");
        seaquake.setColor("Red");
        seaquake.setCost(1);
        seaquake.setAffiliations("The Four Emperors/Whitebeard Pirates");
        seaquake.setEffect("Main If your Leader has {Whitebeard Pirates} in its type, K.O. up to 1 of your opponent's Characters with 3000 power or less.\\nTrigger Give up to 1 of your opponent's Leader or Character cards -3000 power during this turn.");
        seaquake.setImagePath("/images/cards/OP02/OP02-021.png");
        cardRepository.save(seaquake);

        Card whitebeardPirates = new Card();
        whitebeardPirates.setCardNumber("OP02-022");
        whitebeardPirates.setName("Whitebeard Pirates");
        whitebeardPirates.setCardType("Event");
        whitebeardPirates.setColor("Red");
        whitebeardPirates.setCost(1);
        whitebeardPirates.setAffiliations("Whitebeard Pirates");
        whitebeardPirates.setEffect("Main Look at 5 cards from the top of your deck; reveal up to 1 Character card with {Whitebeard Pirates} in its type and add it to your hand. Then, place the rest at the bottom of your deck in any order.\\nTrigger Activate this card's Main effect.");
        whitebeardPirates.setImagePath("/images/cards/OP02/OP02-022.png");
        cardRepository.save(whitebeardPirates);

        Card youMayBeAFool = new Card();
        youMayBeAFool.setCardNumber("OP02-023");
        youMayBeAFool.setName("You May Be a Fool...but I Still Love You");
        youMayBeAFool.setCardType("Event");
        youMayBeAFool.setColor("Red");
        youMayBeAFool.setCost(1);
        youMayBeAFool.setAffiliations("The Four Emperors/Whitebeard Pirates");
        youMayBeAFool.setEffect("Main If you have 3 or less Life cards, you cannot add Life cards to your hand using your own effects during this turn.\\nTrigger Your Leader or up to 1 of your Characters gains +1000 power during this turn.");
        youMayBeAFool.setImagePath("/images/cards/OP02/OP02-023.png");
        cardRepository.save(youMayBeAFool);

        Card mobyDick = new Card();
        mobyDick.setCardNumber("OP02-024");
        mobyDick.setName("Moby Dick");
        mobyDick.setCardType("Stage");
        mobyDick.setColor("Red");
        mobyDick.setCost(2);
        mobyDick.setAffiliations("Whitebeard Pirates");
        mobyDick.setEffect("Your Turn If you have 1 or less Life cards, your [Edward Newgate] and all your Characters with {Whitebeard Pirates} in its type gain +2000 power.\\nTrigger Play this card.");
        mobyDick.setImagePath("/images/cards/OP02/OP02-024.png");
        cardRepository.save(mobyDick);

        // Green Cards
        Card kinemonLeader = new Card();
        kinemonLeader.setCardNumber("OP02-025");
        kinemonLeader.setName("Kin'emon");
        kinemonLeader.setCardType("Leader");
        kinemonLeader.setColor("Green");
        kinemonLeader.setPower(5000);
        kinemonLeader.setLife(5);
        kinemonLeader.setAttribute("Slash");
        kinemonLeader.setAffiliations("Wano Country/Nine Red Scabbards");
        kinemonLeader.setEffect("Activate: Main Once Per Turn When you have 1 or less Characters in play, reduce the play cost of the next 3 cost or higher {Wano Country} type Character card you play from your hand by 1 during this turn.");
        kinemonLeader.setImagePath("/images/cards/OP02/OP02-025.png");
        cardRepository.save(kinemonLeader);

        Card sanjiLeader = new Card();
        sanjiLeader.setCardNumber("OP02-026");
        sanjiLeader.setName("Sanji");
        sanjiLeader.setCardType("Leader");
        sanjiLeader.setColor("Green"); // Assuming Green as primary
        sanjiLeader.setPower(5000);
        sanjiLeader.setLife(4);
        sanjiLeader.setAttribute("Strike");
        sanjiLeader.setAffiliations("Straw Hat Crew");
        sanjiLeader.setEffect("Once Per Turn When you play a Character without an effect from your hand, if you have 3 or less Characters in play, set up to 2 of your Don!! as active.");
        sanjiLeader.setImagePath("/images/cards/OP02/OP02-026.png");
        cardRepository.save(sanjiLeader);

        Card dogStormGreen = new Card();
        dogStormGreen.setCardNumber("OP02-027");
        dogStormGreen.setName("Dog Storm");
        dogStormGreen.setCardType("Character");
        dogStormGreen.setColor("Green");
        dogStormGreen.setCost(3);
        dogStormGreen.setPower(4000);
        dogStormGreen.setCounter(1000);
        dogStormGreen.setAttribute("Slash");
        dogStormGreen.setAffiliations("Mink Tribe/Wano Country/Nine Red Scabbards");
        dogStormGreen.setEffect("If all your DON!! cards are rested, this Character cannot leave the field due to your opponent's effects.");
        dogStormGreen.setImagePath("/images/cards/OP02/OP02-027.png");
        cardRepository.save(dogStormGreen);

        Card usoppGreen = new Card();
        usoppGreen.setCardNumber("OP02-028");
        usoppGreen.setName("Usopp");
        usoppGreen.setCardType("Character");
        usoppGreen.setColor("Green");
        usoppGreen.setCost(3);
        usoppGreen.setPower(5000);
        usoppGreen.setCounter(1000);
        usoppGreen.setAttribute("Ranged");
        usoppGreen.setAffiliations("FILM/Straw Hat Crew");
        usoppGreen.setImagePath("/images/cards/OP02/OP02-028.png");
        cardRepository.save(usoppGreen);

        Card carrotGreen = new Card();
        carrotGreen.setCardNumber("OP02-029");
        carrotGreen.setName("Carrot");
        carrotGreen.setCardType("Character");
        carrotGreen.setColor("Green");
        carrotGreen.setCost(5);
        carrotGreen.setPower(5000);
        carrotGreen.setCounter(2000);
        carrotGreen.setAttribute("Special");
        carrotGreen.setAffiliations("Mink Tribe");
        carrotGreen.setEffect("End of Your Turn Set up to 1 of your DON!! as active.");
        carrotGreen.setImagePath("/images/cards/OP02/OP02-029.png");
        cardRepository.save(carrotGreen);

        Card kozukiOden = new Card();
        kozukiOden.setCardNumber("OP02-030");
        kozukiOden.setName("Kozuki Oden");
        kozukiOden.setCardType("Character");
        kozukiOden.setColor("Green");
        kozukiOden.setCost(8);
        kozukiOden.setPower(8000);
        kozukiOden.setAttribute("Slash");
        kozukiOden.setAffiliations("Wano Country/Kozuki Family");
        kozukiOden.setEffect("Activate: Main Once Per Turn [3] (You may rest the specified number of DON!! cards in your Cost Area): Set this Character as active.\\nOn K.O. Play up to 1 {Wano Country} type Character card with a cost of 3 from your deck. Then, shuffle your deck.");
        kozukiOden.setImagePath("/images/cards/OP02/OP02-030.png");
        cardRepository.save(kozukiOden);

        Card kozukiToki = new Card();
        kozukiToki.setCardNumber("OP02-031");
        kozukiToki.setName("Kozuki Toki");
        kozukiToki.setCardType("Character");
        kozukiToki.setColor("Green");
        kozukiToki.setCost(1);
        kozukiToki.setPower(0);
        kozukiToki.setCounter(1000);
        kozukiToki.setAttribute("Wisdom");
        kozukiToki.setAffiliations("Wano Country/Kozuki Family");
        kozukiToki.setEffect("If you have a [Kozuki Oden] Character in play, this Character gains Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        kozukiToki.setImagePath("/images/cards/OP02/OP02-031.png");
        cardRepository.save(kozukiToki);

        Card shishilian = new Card();
        shishilian.setCardNumber("OP02-032");
        shishilian.setName("Shishilian");
        shishilian.setCardType("Character");
        shishilian.setColor("Green");
        shishilian.setCost(2);
        shishilian.setPower(3000);
        shishilian.setCounter(1000);
        shishilian.setAttribute("Slash");
        shishilian.setAffiliations("Mink Tribe");
        shishilian.setEffect("On Play [2] (You may rest the specified number of DON!! cards in your Cost Area): Set up to 1 of your {Mink Tribe} type Characters with a cost of 5 or less as active.");
        shishilian.setImagePath("/images/cards/OP02/OP02-032.png");
        cardRepository.save(shishilian);

        Card jinbeGreen = new Card();
        jinbeGreen.setCardNumber("OP02-033");
        jinbeGreen.setName("Jinbe");
        jinbeGreen.setCardType("Character");
        jinbeGreen.setColor("Green");
        jinbeGreen.setCost(2);
        jinbeGreen.setPower(4000);
        jinbeGreen.setCounter(1000);
        jinbeGreen.setAttribute("Strike");
        jinbeGreen.setAffiliations("FILM/Fish-Man/Straw Hat Crew");
        jinbeGreen.setImagePath("/images/cards/OP02/OP02-033.png");
        cardRepository.save(jinbeGreen);

        Card tonyTonyChopperGreen = new Card();
        tonyTonyChopperGreen.setCardNumber("OP02-034");
        tonyTonyChopperGreen.setName("Tony Tony.Chopper");
        tonyTonyChopperGreen.setCardType("Character");
        tonyTonyChopperGreen.setColor("Green");
        tonyTonyChopperGreen.setCost(2);
        tonyTonyChopperGreen.setPower(2000);
        tonyTonyChopperGreen.setCounter(2000);
        tonyTonyChopperGreen.setAttribute("Wisdom");
        tonyTonyChopperGreen.setAffiliations("FILM/Animal/Straw Hat Crew");
        tonyTonyChopperGreen.setEffect("DON!!x1 When Attacking Rest up to 1 of your opponent's Characters with a cost of 2 or less.");
        tonyTonyChopperGreen.setImagePath("/images/cards/OP02/OP02-034.png");
        cardRepository.save(tonyTonyChopperGreen);

        Card trafalgarLawGreen = new Card();
        trafalgarLawGreen.setCardNumber("OP02-035");
        trafalgarLawGreen.setName("Trafalgar Law");
        trafalgarLawGreen.setCardType("Character");
        trafalgarLawGreen.setColor("Green");
        trafalgarLawGreen.setCost(2);
        trafalgarLawGreen.setPower(3000);
        trafalgarLawGreen.setCounter(1000);
        trafalgarLawGreen.setAttribute("Slash");
        trafalgarLawGreen.setAffiliations("FILM/Supernovas/Heart Pirates");
        trafalgarLawGreen.setEffect("Activate: Main [1] (You may rest the specified number of DON!! cards in your Cost Area): You may return this Character to the owner's hand: Play up to 1 Character with a cost of 3 from your hand.");
        trafalgarLawGreen.setImagePath("/images/cards/OP02/OP02-035.png");
        cardRepository.save(trafalgarLawGreen);

        Card namiGreen = new Card();
        namiGreen.setCardNumber("OP02-036");
        namiGreen.setName("Nami");
        namiGreen.setCardType("Character");
        namiGreen.setColor("Green");
        namiGreen.setCost(3);
        namiGreen.setPower(5000);
        namiGreen.setAttribute("Special");
        namiGreen.setAffiliations("FILM/Straw Hat Crew");
        namiGreen.setEffect("On Play/When Attacking [1] (You may rest the specified number of DON!! cards in your Cost Area): Look at 3 cards from the top of your deck; reveal up to 1 {FILM} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.");
        namiGreen.setImagePath("/images/cards/OP02/OP02-036.png");
        cardRepository.save(namiGreen);

        Card nicoRobinGreen = new Card();
        nicoRobinGreen.setCardNumber("OP02-037");
        nicoRobinGreen.setName("Nico Robin");
        nicoRobinGreen.setCardType("Character");
        nicoRobinGreen.setColor("Green");
        nicoRobinGreen.setCost(3);
        nicoRobinGreen.setPower(4000);
        nicoRobinGreen.setCounter(1000);
        nicoRobinGreen.setAttribute("Strike");
        nicoRobinGreen.setAffiliations("FILM/Straw Hat Crew");
        nicoRobinGreen.setEffect("On Play Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 2 or less from your hand.");
        nicoRobinGreen.setImagePath("/images/cards/OP02/OP02-037.png");
        cardRepository.save(nicoRobinGreen);

        Card catViperGreen = new Card();
        catViperGreen.setCardNumber("OP02-038");
        catViperGreen.setName("Cat Viper");
        catViperGreen.setCardType("Character");
        catViperGreen.setColor("Green");
        catViperGreen.setCost(3);
        catViperGreen.setPower(4000);
        catViperGreen.setCounter(1000);
        catViperGreen.setAttribute("Slash");
        catViperGreen.setAffiliations("Mink Tribe/Wano Country/Nine Red Scabbards");
        catViperGreen.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        catViperGreen.setImagePath("/images/cards/OP02/OP02-038.png");
        cardRepository.save(catViperGreen);

        Card frankyGreen = new Card();
        frankyGreen.setCardNumber("OP02-039");
        frankyGreen.setName("Franky");
        frankyGreen.setCardType("Character");
        frankyGreen.setColor("Green");
        frankyGreen.setCost(5);
        frankyGreen.setPower(7000);
        frankyGreen.setCounter(1000);
        frankyGreen.setAttribute("Special");
        frankyGreen.setAffiliations("FILM/Straw Hat Crew");
        frankyGreen.setImagePath("/images/cards/OP02/OP02-039.png");
        cardRepository.save(frankyGreen);

        Card brookGreen = new Card();
        brookGreen.setCardNumber("OP02-040");
        brookGreen.setName("Brook");
        brookGreen.setCardType("Character");
        brookGreen.setColor("Green");
        brookGreen.setCost(4);
        brookGreen.setPower(5000);
        brookGreen.setCounter(1000);
        brookGreen.setAttribute("Slash");
        brookGreen.setAffiliations("FILM/Straw Hat Crew");
        brookGreen.setEffect("On Play Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 3 or less from your hand.");
        brookGreen.setImagePath("/images/cards/OP02/OP02-040.png");
        cardRepository.save(brookGreen);

        Card monkeyDLuffyGreen = new Card();
        monkeyDLuffyGreen.setCardNumber("OP02-041");
        monkeyDLuffyGreen.setName("Monkey. D. Luffy");
        monkeyDLuffyGreen.setCardType("Character");
        monkeyDLuffyGreen.setColor("Green");
        monkeyDLuffyGreen.setCost(7);
        monkeyDLuffyGreen.setPower(7000);
        monkeyDLuffyGreen.setAttribute("Strike");
        monkeyDLuffyGreen.setAffiliations("FILM/Supernovas/Straw Hat Crew");
        monkeyDLuffyGreen.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\\nOn Play Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 4 or less from your hand.");
        monkeyDLuffyGreen.setImagePath("/images/cards/OP02/OP02-041.png");
        cardRepository.save(monkeyDLuffyGreen);

        Card yamatoGreen = new Card();
        yamatoGreen.setCardNumber("OP02-042");
        yamatoGreen.setName("Yamato");
        yamatoGreen.setCardType("Character");
        yamatoGreen.setColor("Green");
        yamatoGreen.setCost(4);
        yamatoGreen.setPower(6000);
        yamatoGreen.setAttribute("Strike");
        yamatoGreen.setAffiliations("Wano Country");
        yamatoGreen.setEffect("This card's name is also treated as [Kozuki Oden].\\nOn Play Rest up to 1 of your opponents Characters with a cost of 6 or less.");
        yamatoGreen.setImagePath("/images/cards/OP02/OP02-042.png");
        cardRepository.save(yamatoGreen);

        Card roronoaZoroGreen = new Card();
        roronoaZoroGreen.setCardNumber("OP02-043");
        roronoaZoroGreen.setName("Roronoa Zoro");
        roronoaZoroGreen.setCardType("Character");
        roronoaZoroGreen.setColor("Green");
        roronoaZoroGreen.setCost(4);
        roronoaZoroGreen.setPower(6000);
        roronoaZoroGreen.setCounter(1000);
        roronoaZoroGreen.setAttribute("Slash");
        roronoaZoroGreen.setAffiliations("FILM/Supernovas/Straw Hat Crew");
        roronoaZoroGreen.setImagePath("/images/cards/OP02/OP02-043.png");
        cardRepository.save(roronoaZoroGreen);

        Card wanda = new Card();
        wanda.setCardNumber("OP02-044");
        wanda.setName("Wanda");
        wanda.setCardType("Character");
        wanda.setColor("Green");
        wanda.setCost(2);
        wanda.setPower(3000);
        wanda.setCounter(1000);
        wanda.setAttribute("Slash");
        wanda.setAffiliations("Mink Tribe");
        wanda.setEffect("On Play Play up to 1 {Mink Tribe} type Character card other than [Wanda] with a cost of 3 or less from your hand.");
        wanda.setImagePath("/images/cards/OP02/OP02-044.png");
        cardRepository.save(wanda);
        
        // Green Events & Stages
        Card threeSwordStyleOniGiri = new Card();
        threeSwordStyleOniGiri.setCardNumber("OP02-045");
        threeSwordStyleOniGiri.setName("Three Sword Style: Oni Giri");
        threeSwordStyleOniGiri.setCardType("Event");
        threeSwordStyleOniGiri.setColor("Green");
        threeSwordStyleOniGiri.setCost(3);
        threeSwordStyleOniGiri.setAffiliations("FILM/Supernovas/Straw Hat Crew");
        threeSwordStyleOniGiri.setEffect("Counter Your Leader or up to 1 of your Characters gains +6000 Power during this battle. Then, you may play up to 1 Character with a cost of 3 or less without an effect from your hand.\\nTrigger Rest up to 1 of your opponent's Leader or Characters with a cost of 5 or lower.");
        threeSwordStyleOniGiri.setImagePath("/images/cards/OP02/OP02-045.png");
        cardRepository.save(threeSwordStyleOniGiri);

        Card diableJambeVenaisonShoot = new Card();
        diableJambeVenaisonShoot.setCardNumber("OP02-046");
        diableJambeVenaisonShoot.setName("Diable Jambe Venaison Shoot");
        diableJambeVenaisonShoot.setCardType("Event");
        diableJambeVenaisonShoot.setColor("Green");
        diableJambeVenaisonShoot.setCost(2);
        diableJambeVenaisonShoot.setAffiliations("FILM/Straw Hat Crew");
        diableJambeVenaisonShoot.setEffect("Main K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less\\nTrigger Play up to 1 Character with a cost of 4 or less without an effect from your hand.");
        diableJambeVenaisonShoot.setImagePath("/images/cards/OP02/OP02-046.png");
        cardRepository.save(diableJambeVenaisonShoot);

        Card paradiseTotsuka = new Card();
        paradiseTotsuka.setCardNumber("OP02-047");
        paradiseTotsuka.setName("Paradise Totsuka");
        paradiseTotsuka.setCardType("Event");
        paradiseTotsuka.setColor("Green");
        paradiseTotsuka.setCost(1);
        paradiseTotsuka.setAffiliations("Wano Country/Kozuki Family");
        paradiseTotsuka.setEffect("Main Rest up to 1 of your opponent's Characters with a cost of 4 or less.\\nTrigger K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.");
        paradiseTotsuka.setImagePath("/images/cards/OP02/OP02-047.png");
        cardRepository.save(paradiseTotsuka);

        Card flowerCapital = new Card();
        flowerCapital.setCardNumber("OP02-048");
        flowerCapital.setName("Flower Capital");
        flowerCapital.setCardType("Stage");
        flowerCapital.setColor("Green");
        flowerCapital.setCost(1);
        flowerCapital.setAffiliations("Wano Country");
        flowerCapital.setEffect("Activate: Main You may trash 1 {Wano Country} type card and rest this card: Set up to 1 of your DON!! cards as active.");
        flowerCapital.setImagePath("/images/cards/OP02/OP02-048.png");
        cardRepository.save(flowerCapital);

        // Blue Cards
        Card emporioIvankovLeader = new Card();
        emporioIvankovLeader.setCardNumber("OP02-049");
        emporioIvankovLeader.setName("Emporio Ivankov");
        emporioIvankovLeader.setCardType("Leader");
        emporioIvankovLeader.setColor("Blue");
        emporioIvankovLeader.setPower(5000);
        emporioIvankovLeader.setLife(5);
        emporioIvankovLeader.setAttribute("Special");
        emporioIvankovLeader.setAffiliations("Impel Down/Revolutionary Army");
        emporioIvankovLeader.setEffect("End of Your Turn If you have 0 cards in your hand, draw 2 cards.");
        emporioIvankovLeader.setImagePath("/images/cards/OP02/OP02-049.png");
        cardRepository.save(emporioIvankovLeader);
        
        Card zLeader = new Card();
        zLeader.setCardNumber("OP02-050");
        zLeader.setName("Z");
        zLeader.setCardType("Leader");
        zLeader.setColor("Purple"); // Assuming Purple as primary
        zLeader.setPower(5000);
        zLeader.setLife(4);
        zLeader.setAttribute("Special");
        zLeader.setAffiliations("FILM/Neo Navy");
        zLeader.setEffect("When Attacking DON!! -4 (You may return the specified number of DON!! cards from your field to your DON!! deck): K.O. up to 1 of your opponent's Characters with a cost of 3 or less. Then, this Leader gains +1000 Power during this turn.");
        zLeader.setImagePath("/images/cards/OP02/OP02-050.png");
        cardRepository.save(zLeader);
        
        Card emporioIvankov = new Card();
        emporioIvankov.setCardNumber("OP02-051");
        emporioIvankov.setName("Emporio Ivankov");
        emporioIvankov.setCardType("Character");
        emporioIvankov.setColor("Blue");
        emporioIvankov.setCost(7);
        emporioIvankov.setPower(7000);
        emporioIvankov.setAttribute("Special");
        emporioIvankov.setAffiliations("Impel Down/Revolutionary Army");
        emporioIvankov.setEffect("On Play Draw cards until you have 3 cards in your hand, then play up to 1 blue {Impel Down} type Character card with a cost of 6 or less from your hand.");
        emporioIvankov.setImagePath("/images/cards/OP02/OP02-051.png");
        cardRepository.save(emporioIvankov);

        Card cabaji = new Card();
        cabaji.setCardNumber("OP02-052");
        cabaji.setName("Cabaji");
        cabaji.setCardType("Character");
        cabaji.setColor("Blue");
        cabaji.setCost(2);
        cabaji.setPower(3000);
        cabaji.setCounter(1000);
        cabaji.setAttribute("Slash");
        cabaji.setAffiliations("Buggy Pirates");
        cabaji.setEffect("On Play If you have [Mohji] in play, draw 2 cards and trash 1 card from your hand.");
        cabaji.setImagePath("/images/cards/OP02/OP02-052.png");
        cardRepository.save(cabaji);

        Card crocodileBlue = new Card();
        crocodileBlue.setCardNumber("OP02-053");
        crocodileBlue.setName("Crocodile");
        crocodileBlue.setCardType("Character");
        crocodileBlue.setColor("Blue");
        crocodileBlue.setCost(5);
        crocodileBlue.setPower(7000);
        crocodileBlue.setCounter(1000);
        crocodileBlue.setAttribute("Special");
        crocodileBlue.setAffiliations("Impel Down/Former Baroque Works");
        crocodileBlue.setImagePath("/images/cards/OP02/OP02-053.png");
        cardRepository.save(crocodileBlue);

        Card geckoMoriaBlue = new Card();
        geckoMoriaBlue.setCardNumber("OP02-054");
        geckoMoriaBlue.setName("Gecko Moria");
        geckoMoriaBlue.setCardType("Character");
        geckoMoriaBlue.setColor("Blue");
        geckoMoriaBlue.setCost(4);
        geckoMoriaBlue.setPower(6000);
        geckoMoriaBlue.setCounter(1000);
        geckoMoriaBlue.setAttribute("Special");
        geckoMoriaBlue.setAffiliations("The Seven Warlords of the Sea/Thriller Bark Pirates");
        geckoMoriaBlue.setImagePath("/images/cards/OP02/OP02-054.png");
        cardRepository.save(geckoMoriaBlue);

        Card draculeMihawkBlue = new Card();
        draculeMihawkBlue.setCardNumber("OP02-055");
        draculeMihawkBlue.setName("Dracule Mihawk");
        draculeMihawkBlue.setCardType("Character");
        draculeMihawkBlue.setColor("Blue");
        draculeMihawkBlue.setCost(6);
        draculeMihawkBlue.setPower(8000);
        draculeMihawkBlue.setCounter(1000);
        draculeMihawkBlue.setAttribute("Slash");
        draculeMihawkBlue.setAffiliations("The Seven Warlords of the Sea");
        draculeMihawkBlue.setImagePath("/images/cards/OP02/OP02-055.png");
        cardRepository.save(draculeMihawkBlue);

        Card donquixoteDoflamingo = new Card();
        donquixoteDoflamingo.setCardNumber("OP02-056");
        donquixoteDoflamingo.setName("Donquixote Doflamingo");
        donquixoteDoflamingo.setCardType("Character");
        donquixoteDoflamingo.setColor("Blue");
        donquixoteDoflamingo.setCost(1);
        donquixoteDoflamingo.setPower(2000);
        donquixoteDoflamingo.setCounter(1000);
        donquixoteDoflamingo.setAttribute("Special");
        donquixoteDoflamingo.setAffiliations("The Seven Warlords of the Sea/Donquixote Pirates");
        donquixoteDoflamingo.setEffect("On Play Look at 3 cards from the top of your deck and return them to the top or bottom of the deck in any order.\\nDON!!x1 When Attacking Trash 1 card from your hand: Place up to 1 of your opponent's Characters with a cost of 1 or less to the bottom of the deck.");
        donquixoteDoflamingo.setImagePath("/images/cards/OP02/OP02-056.png");
        cardRepository.save(donquixoteDoflamingo);

        Card bartholomewKuma = new Card();
        bartholomewKuma.setCardNumber("OP02-057");
        bartholomewKuma.setName("Bartholomew Kuma");
        bartholomewKuma.setCardType("Character");
        bartholomewKuma.setColor("Blue");
        bartholomewKuma.setCost(3);
        bartholomewKuma.setPower(3000);
        bartholomewKuma.setCounter(1000);
        bartholomewKuma.setAttribute("Strike");
        bartholomewKuma.setAffiliations("The Seven Warlords of the Sea/Revolutionary Army");
        bartholomewKuma.setEffect("On Play Look at 2 cards from the top of your deck; reveal up to 1 {The Seven Warlords of the Sea} type card and add it to your hand. Then, place the rest at the top or bottom of the deck in any order.");
        bartholomewKuma.setImagePath("/images/cards/OP02/OP02-057.png");
        cardRepository.save(bartholomewKuma);

        Card buggyBlue = new Card();
        buggyBlue.setCardNumber("OP02-058");
        buggyBlue.setName("Buggy");
        buggyBlue.setCardType("Character");
        buggyBlue.setColor("Blue");
        buggyBlue.setCost(1);
        buggyBlue.setPower(2000);
        buggyBlue.setCounter(1000);
        buggyBlue.setAttribute("Slash");
        buggyBlue.setAffiliations("Impel Down/Buggy Pirates");
        buggyBlue.setEffect("On Play Look at 5 cards from the top of your deck; reveal up to 1 Blue {Impel Down} type card other than [Buggy] and add it to your hand. Then place the rest at the bottom of your deck in any order.");
        buggyBlue.setImagePath("/images/cards/OP02/OP02-058.png");
        cardRepository.save(buggyBlue);

        Card boaHancockBlue = new Card();
        boaHancockBlue.setCardNumber("OP02-059");
        boaHancockBlue.setName("Boa Hancock");
        boaHancockBlue.setCardType("Character");
        boaHancockBlue.setColor("Blue");
        boaHancockBlue.setCost(4);
        boaHancockBlue.setPower(5000);
        boaHancockBlue.setCounter(1000);
        boaHancockBlue.setAttribute("Special");
        boaHancockBlue.setAffiliations("Impel Down/The Seven Warlords of the Sea/Kuja Pirates");
        boaHancockBlue.setEffect("When Attacking Draw 1 card and trash 1 card from your hand. Then, trash up to 3 cards from your hand.");
        boaHancockBlue.setImagePath("/images/cards/OP02/OP02-059.png");
        cardRepository.save(boaHancockBlue);

        Card mohji = new Card();
        mohji.setCardNumber("OP02-060");
        mohji.setName("Mohji");
        mohji.setCardType("Character");
        mohji.setColor("Blue");
        mohji.setCost(1);
        mohji.setPower(3000);
        mohji.setCounter(1000);
        mohji.setAttribute("Wisdom");
        mohji.setAffiliations("Buggy Pirates");
        mohji.setImagePath("/images/cards/OP02/OP02-060.png");
        cardRepository.save(mohji);

        Card morley = new Card();
        morley.setCardNumber("OP02-061");
        morley.setName("Morley");
        morley.setCardType("Character");
        morley.setColor("Blue");
        morley.setCost(4);
        morley.setPower(5000);
        morley.setCounter(1000);
        morley.setAttribute("Strike");
        morley.setAffiliations("Giants/Revolutionary Army");
        morley.setEffect("When Attacking If you have 1 or less cards in your hand, your opponent cannot activate a Blocker Character with a cost of 5 or less during this battle.");
        morley.setImagePath("/images/cards/OP02/OP02-061.png");
        cardRepository.save(morley);

        Card monkeyDLuffyBlue = new Card();
        monkeyDLuffyBlue.setCardNumber("OP02-062");
        monkeyDLuffyBlue.setName("Monkey. D. Luffy");
        monkeyDLuffyBlue.setCardType("Character");
        monkeyDLuffyBlue.setColor("Blue");
        monkeyDLuffyBlue.setCost(6);
        monkeyDLuffyBlue.setPower(7000);
        monkeyDLuffyBlue.setAttribute("Strike");
        monkeyDLuffyBlue.setAffiliations("Impel Down/Straw Hat Crew");
        monkeyDLuffyBlue.setEffect("On Play/When Attacking You may trash 2 cards from your hand: Return up to 1 Character with a cost of 4 or less to the owner's hand. Then, this Character gains Double Attack during this turn.");
        monkeyDLuffyBlue.setImagePath("/images/cards/OP02/OP02-062.png");
        cardRepository.save(monkeyDLuffyBlue);

        Card mr1Blue = new Card();
        mr1Blue.setCardNumber("OP02-063");
        mr1Blue.setName("Mr.1(Daz.Bonez)");
        mr1Blue.setCardType("Character");
        mr1Blue.setColor("Blue");
        mr1Blue.setCost(1);
        mr1Blue.setPower(1000);
        mr1Blue.setCounter(1000);
        mr1Blue.setAttribute("Slash");
        mr1Blue.setAffiliations("Impel Down/Former Baroque Works");
        mr1Blue.setEffect("On Play Add up to 1 blue Event card with a cost of 1 from your trash to your hand.");
        mr1Blue.setImagePath("/images/cards/OP02/OP02-063.png");
        cardRepository.save(mr1Blue);

        Card mr2Blue = new Card();
        mr2Blue.setCardNumber("OP02-064");
        mr2Blue.setName("Mr. 2 Bon Clay (Bentham)");
        mr2Blue.setCardType("Character");
        mr2Blue.setColor("Blue");
        mr2Blue.setCost(5);
        mr2Blue.setPower(5000);
        mr2Blue.setCounter(2000);
        mr2Blue.setAttribute("Strike");
        mr2Blue.setAffiliations("Impel Down/Former Baroque Works");
        mr2Blue.setEffect("DON!!x1 When Attacking You may trash 1 card from your hand: Return up to 1 Character with a cost of 2 or less to the bottom of its owner's deck. Then, when this battle ends, return this Character to the bottom of its owner's deck.");
        mr2Blue.setImagePath("/images/cards/OP02/OP02-064.png");
        cardRepository.save(mr2Blue);

        Card mr3Blue = new Card();
        mr3Blue.setCardNumber("OP02-065");
        mr3Blue.setName("Mr. 3 (Galdino)");
        mr3Blue.setCardType("Character");
        mr3Blue.setColor("Blue");
        mr3Blue.setCost(4);
        mr3Blue.setPower(5000);
        mr3Blue.setCounter(1000);
        mr3Blue.setAttribute("Special");
        mr3Blue.setAffiliations("Impel Down/Former Baroque Works");
        mr3Blue.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\\nEnd of Your Turn You may trash 1 card from your hand: Set this card as active.");
        mr3Blue.setImagePath("/images/cards/OP02/OP02-065.png");
        cardRepository.save(mr3Blue);
        
        // Blue Events & Stages
        Card impelDownAllStars = new Card();
        impelDownAllStars.setCardNumber("OP02-066");
        impelDownAllStars.setName("Impel Down All Stars");
        impelDownAllStars.setCardType("Event");
        impelDownAllStars.setColor("Blue");
        impelDownAllStars.setCost(1);
        impelDownAllStars.setAffiliations("Impel Down");
        impelDownAllStars.setEffect("Main You may trash 2 cards from your hand: If your Leader has the {Impel Down} type, draw up to 2 cards.\\nTrigger Draw 2 cards.");
        impelDownAllStars.setImagePath("/images/cards/OP02/OP02-066.png");
        cardRepository.save(impelDownAllStars);

        Card arabesqueBrickFist = new Card();
        arabesqueBrickFist.setCardNumber("OP02-067");
        arabesqueBrickFist.setName("Arabesque Brick Fist");
        arabesqueBrickFist.setCardType("Event");
        arabesqueBrickFist.setColor("Blue");
        arabesqueBrickFist.setCost(2);
        arabesqueBrickFist.setAffiliations("Fish-man/Impel Down");
        arabesqueBrickFist.setEffect("Main Return up to 1 Character with a cost of 4 or less to the owner's hand.\\nTrigger Activate this card's Main effect.");
        arabesqueBrickFist.setImagePath("/images/cards/OP02/OP02-067.png");
        cardRepository.save(arabesqueBrickFist);

        Card gumGumRain = new Card();
        gumGumRain.setCardNumber("OP02-068");
        gumGumRain.setName("Gum Gum Rain");
        gumGumRain.setCardType("Event");
        gumGumRain.setColor("Blue");
        gumGumRain.setCost(0);
        gumGumRain.setAffiliations("Impel Down/Straw Hat Pirates");
        gumGumRain.setEffect("Counter You may trash 1 card from your hand: Your Leader or up to 1 of your Characters gains +3000 Power during this battle.\\nTrigger Return up to 1 Character with a cost of 2 or less to the owner's hand.");
        gumGumRain.setImagePath("/images/cards/OP02/OP02-068.png");
        cardRepository.save(gumGumRain);

        Card deathWink = new Card();
        deathWink.setCardNumber("OP02-069");
        deathWink.setName("Death Wink");
        deathWink.setCardType("Event");
        deathWink.setColor("Blue");
        deathWink.setCost(3);
        deathWink.setAffiliations("Impel Down/Revolutionary Army");
        deathWink.setEffect("Counter Your Leader or up to 1 of your Characters gains +6000 Power during this battle. Then, draw cards until you have 2 cards in your hand.\\nTrigger Return up to 1 Character with a cost of 7 or less to the owner's hand.");
        deathWink.setImagePath("/images/cards/OP02/OP02-069.png");
        cardRepository.save(deathWink);

        Card newKamaLand = new Card();
        newKamaLand.setCardNumber("OP02-070");
        newKamaLand.setName("New Kama Land");
        newKamaLand.setCardType("Stage");
        newKamaLand.setColor("Blue");
        newKamaLand.setCost(1);
        newKamaLand.setAffiliations("Impel Down");
        newKamaLand.setEffect("Activate: Main You may rest this Stage: If your Leader is [Emporio Ivankov], draw 1 card and trash 1 card from your hand. Then, trash up to 3 cards from your hand.");
        newKamaLand.setImagePath("/images/cards/OP02/OP02-070.png");
        cardRepository.save(newKamaLand);
        
        // Purple Cards
        Card magellanLeader = new Card();
        magellanLeader.setCardNumber("OP02-071");
        magellanLeader.setName("Magellan");
        magellanLeader.setCardType("Leader");
        magellanLeader.setColor("Purple");
        magellanLeader.setPower(5000);
        magellanLeader.setLife(5);
        magellanLeader.setAttribute("Special");
        magellanLeader.setAffiliations("Impel Down");
        magellanLeader.setEffect("Your Turn Once Per Turn When a DON!! card is returned from the field to the DON!! deck, this Leader gains +1000 Power during this turn.");
        magellanLeader.setImagePath("/images/cards/OP02/OP02-071.png");
        cardRepository.save(magellanLeader);

        Card zLeaderPurple = new Card(); // Already added as OP02-050, assuming Purple is secondary for 072
        zLeaderPurple.setCardNumber("OP02-072");
        zLeaderPurple.setName("Z");
        zLeaderPurple.setCardType("Leader");
        zLeaderPurple.setColor("Purple");
        zLeaderPurple.setPower(5000);
        zLeaderPurple.setLife(4);
        zLeaderPurple.setAttribute("Special");
        zLeaderPurple.setAffiliations("FILM/Neo Navy");
        zLeaderPurple.setEffect("When Attacking DON!! -4 (You may return the specified number of DON!! cards from your field to your DON!! deck): K.O. up to 1 of your opponent's Characters with a cost of 3 or less. Then, this Leader gains +1000 Power during this turn.");
        zLeaderPurple.setImagePath("/images/cards/OP02/OP02-072.png");
        cardRepository.save(zLeaderPurple);

        Card sadi = new Card();
        sadi.setCardNumber("OP02-073");
        sadi.setName("Sadi");
        sadi.setCardType("Character");
        sadi.setColor("Purple");
        sadi.setCost(3);
        sadi.setPower(3000);
        sadi.setCounter(2000);
        sadi.setAttribute("Wisdom");
        sadi.setAffiliations("Impel Down");
        sadi.setEffect("On Play Play up to 1 {Jailer Beast} type Character card from your hand.");
        sadi.setImagePath("/images/cards/OP02/OP02-073.png");
        cardRepository.save(sadi);

        Card saldeath = new Card();
        saldeath.setCardNumber("OP02-074");
        saldeath.setName("Saldeath");
        saldeath.setCardType("Character");
        saldeath.setColor("Purple");
        saldeath.setCost(1);
        saldeath.setPower(2000);
        saldeath.setCounter(1000);
        saldeath.setAttribute("Wisdom");
        saldeath.setAffiliations("Impel Down");
        saldeath.setEffect("Your [Blugori] gains Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        saldeath.setImagePath("/images/cards/OP02/OP02-074.png");
        cardRepository.save(saldeath);

        Card shiki = new Card();
        shiki.setCardNumber("OP02-075");
        shiki.setName("Shiki");
        shiki.setCardType("Character");
        shiki.setColor("Purple");
        shiki.setCost(2);
        shiki.setPower(3000);
        shiki.setCounter(2000);
        shiki.setAttribute("Slash");
        shiki.setAffiliations("FILM/Golden Lion Pirates");
        shiki.setEffect("Trigger DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck): Play this card.");
        shiki.setImagePath("/images/cards/OP02/OP02-075.png");
        cardRepository.save(shiki);

        Card shiryu = new Card();
        shiryu.setCardNumber("OP02-076");
        shiryu.setName("Shiryu");
        shiryu.setCardType("Character");
        shiryu.setColor("Purple");
        shiryu.setCost(4);
        shiryu.setPower(5000);
        shiryu.setCounter(1000);
        shiryu.setAttribute("Slash");
        shiryu.setAffiliations("Impel Down");
        shiryu.setEffect("On Play DON!! -1 (You may return the specified number of DON!! cards on the field to their DON!! deck): K.O. up to 1 of your opponent's Characters with a cost of 1 or less.");
        shiryu.setImagePath("/images/cards/OP02/OP02-076.png");
        cardRepository.save(shiryu);

        Card solitaire = new Card();
        solitaire.setCardNumber("OP02-077");
        solitaire.setName("Solitaire");
        solitaire.setCardType("Character");
        solitaire.setColor("Purple");
        solitaire.setCost(3);
        solitaire.setPower(5000);
        solitaire.setCounter(1000);
        solitaire.setAttribute("Slash");
        solitaire.setAffiliations("Animal Kingdom Pirates/SMILE");
        solitaire.setImagePath("/images/cards/OP02/OP02-077.png");
        cardRepository.save(solitaire);

        Card daifugo = new Card();
        daifugo.setCardNumber("OP02-078");
        daifugo.setName("Daifugo");
        daifugo.setCardType("Character");
        daifugo.setColor("Purple");
        daifugo.setCost(3);
        daifugo.setPower(5000);
        daifugo.setCounter(1000);
        daifugo.setAttribute("Ranged");
        daifugo.setAffiliations("Animal Kingdom Pirates/SMILE");
        daifugo.setEffect("On Play DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck): Play up to 1 {SMILE} type Character card other than [Daifugo] with a cost of 3 or less from your hand.");
        daifugo.setImagePath("/images/cards/OP02/OP02-078.png");
        cardRepository.save(daifugo);

        Card douglasBullet = new Card();
        douglasBullet.setCardNumber("OP02-079");
        douglasBullet.setName("Douglas Bullet");
        douglasBullet.setCardType("Character");
        douglasBullet.setColor("Purple");
        douglasBullet.setCost(5);
        douglasBullet.setPower(6000);
        douglasBullet.setCounter(1000);
        douglasBullet.setAttribute("Special");
        douglasBullet.setAffiliations("FILM/The Pirates Fest");
        douglasBullet.setEffect("On Play DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck): Rest up to 1 of your opponent's Characters with a cost of 4 or less.");
        douglasBullet.setImagePath("/images/cards/OP02/OP02-079.png");
        cardRepository.save(douglasBullet);

        Card dobon = new Card();
        dobon.setCardNumber("OP02-080");
        dobon.setName("Dobon");
        dobon.setCardType("Character");
        dobon.setColor("Purple");
        dobon.setCost(2);
        dobon.setPower(4000);
        dobon.setCounter(1000);
        dobon.setAttribute("Strike");
        dobon.setAffiliations("Animal Kingdom Pirates/SMILE");
        dobon.setImagePath("/images/cards/OP02/OP02-080.png");
        cardRepository.save(dobon);

        Card domino = new Card();
        domino.setCardNumber("OP02-081");
        domino.setName("Domino");
        domino.setCardType("Character");
        domino.setColor("Purple");
        domino.setCost(2);
        domino.setPower(2000);
        domino.setCounter(1000);
        domino.setAttribute("Wisdom");
        domino.setAffiliations("Impel Down");
        domino.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        domino.setImagePath("/images/cards/OP02/OP02-081.png");
        cardRepository.save(domino);

        Card byrnndiWorld = new Card();
        byrnndiWorld.setCardNumber("OP02-082");
        byrnndiWorld.setName("Byrnndi World");
        byrnndiWorld.setCardType("Character");
        byrnndiWorld.setColor("Purple");
        byrnndiWorld.setCost(8);
        byrnndiWorld.setPower(8000);
        byrnndiWorld.setAttribute("Strike");
        byrnndiWorld.setAffiliations("World Pirates");
        byrnndiWorld.setEffect("Activate: Main DON!! -8 (You may return the specified number of DON!! cards from your field to your DON!! deck): This Character gains +792000 Power during this turn."); // Power boost seems excessive, verify later
        byrnndiWorld.setImagePath("/images/cards/OP02/OP02-082.png");
        cardRepository.save(byrnndiWorld);

        Card hanyabal = new Card();
        hanyabal.setCardNumber("OP02-083");
        hanyabal.setName("Hanyabal");
        hanyabal.setCardType("Character");
        hanyabal.setColor("Purple");
        hanyabal.setCost(1);
        hanyabal.setPower(2000);
        hanyabal.setCounter(1000);
        hanyabal.setAttribute("Slash");
        hanyabal.setAffiliations("Impel Down");
        hanyabal.setEffect("On Play Look at 5 cards from the top of your deck; reveal up to 1 purple {Impel Down} type card other than [Hanyabal] and add it to your hand. Then, place the rest at the bottom of your deck in any order.");
        hanyabal.setImagePath("/images/cards/OP02/OP02-083.png");
        cardRepository.save(hanyabal);

        Card blugori = new Card();
        blugori.setCardNumber("OP02-084");
        blugori.setName("Blugori");
        blugori.setCardType("Character");
        blugori.setColor("Purple");
        blugori.setCost(1);
        blugori.setPower(3000);
        blugori.setCounter(1000);
        blugori.setAttribute("Slash");
        blugori.setAffiliations("Animal/Impel Down");
        blugori.setImagePath("/images/cards/OP02/OP02-084.png");
        cardRepository.save(blugori);

        Card magellan = new Card();
        magellan.setCardNumber("OP02-085");
        magellan.setName("Magellan");
        magellan.setCardType("Character");
        magellan.setColor("Purple");
        magellan.setCost(5);
        magellan.setPower(6000);
        magellan.setAttribute("Special");
        magellan.setAffiliations("Impel Down");
        magellan.setEffect("On Play DON!! -1: Your opponent returns 1 of their DON!! cards on the field to their DON!! deck.\\nOpponent's Turn When this Character is K.O.ed, your opponent returns 2 of their DON!! cards on the field to their DON!! deck.");
        magellan.setImagePath("/images/cards/OP02/OP02-085.png");
        cardRepository.save(magellan);

        Card minokoala = new Card();
        minokoala.setCardNumber("OP02-086");
        minokoala.setName("Minokoala");
        minokoala.setCardType("Character");
        minokoala.setColor("Purple");
        minokoala.setCost(4);
        minokoala.setPower(5000);
        minokoala.setCounter(1000);
        minokoala.setAttribute("Strike");
        minokoala.setAffiliations("Impel Down/Jailer Beast");
        minokoala.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\\nOn K.O. If your Leader has the {Impel Down} type, add 1 DON!! card from your DON!! deck and rest it.");
        minokoala.setImagePath("/images/cards/OP02/OP02-086.png");
        cardRepository.save(minokoala);

        Card minotaur = new Card();
        minotaur.setCardNumber("OP02-087");
        minotaur.setName("Minotaur");
        minotaur.setCardType("Character");
        minotaur.setColor("Purple");
        minotaur.setCost(4);
        minotaur.setPower(5000);
        minotaur.setCounter(1000);
        minotaur.setAttribute("Strike");
        minotaur.setAffiliations("Impel Down/Jailer Beast");
        minotaur.setEffect("Double Attack (This card deals 2 damage.)\\nOn K.O. If your Leader has the {Impel Down} type, add 1 DON!! card from your DON!! deck and rest it.");
        minotaur.setImagePath("/images/cards/OP02/OP02-087.png");
        cardRepository.save(minotaur);

        Card sphinx = new Card();
        sphinx.setCardNumber("OP02-088");
        sphinx.setName("Sphinx");
        sphinx.setCardType("Character");
        sphinx.setColor("Purple");
        sphinx.setCost(4);
        sphinx.setPower(6000);
        sphinx.setCounter(1000);
        sphinx.setAttribute("Strike");
        sphinx.setAffiliations("Animal/Impel Down");
        sphinx.setImagePath("/images/cards/OP02/OP02-088.png");
        cardRepository.save(sphinx);
        
        // Purple Events & Stages
        Card hellsJudgement = new Card();
        hellsJudgement.setCardNumber("OP02-089");
        hellsJudgement.setName("Hell's Judgement");
        hellsJudgement.setCardType("Event");
        hellsJudgement.setColor("Purple");
        hellsJudgement.setCost(2);
        hellsJudgement.setAffiliations("Impel Down");
        hellsJudgement.setEffect("Counter DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck): Give up to 2 of your opponent's Leader or Characters -3000 Power during this turn.\\nTrigger If your opponent has 6 or more DON!! cards, your opponent returns 1 of their DON!! cards to their DON!! deck.");
        hellsJudgement.setImagePath("/images/cards/OP02/OP02-089.png");
        cardRepository.save(hellsJudgement);

        Card hydra = new Card();
        hydra.setCardNumber("OP02-090");
        hydra.setName("Hydra");
        hydra.setCardType("Event");
        hydra.setColor("Purple");
        hydra.setCost(1);
        hydra.setAffiliations("Impel Down");
        hydra.setEffect("Main DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Give up to 1 of your opponent's Characters -3000 power during this turn.\\nTrigger If your opponent has 6 or more DON!! cards, your opponent returns 1 of their DON!! cards to their DON!! deck.");
        hydra.setImagePath("/images/cards/OP02/OP02-090.png");
        cardRepository.save(hydra);

        Card venomRoad = new Card();
        venomRoad.setCardNumber("OP02-091");
        venomRoad.setName("Venom Road");
        venomRoad.setCardType("Event");
        venomRoad.setColor("Purple");
        venomRoad.setCost(3);
        venomRoad.setAffiliations("Impel Down");
        venomRoad.setEffect("Main Add up to 1 DON!! card from your DON!! deck and set it as active.\\nTrigger If your opponent has 6 or more DON!! cards, your opponent returns 1 of their DON!! cards to their DON!! deck.");
        venomRoad.setImagePath("/images/cards/OP02/OP02-091.png");
        cardRepository.save(venomRoad);

        Card impelDownStage = new Card();
        impelDownStage.setCardNumber("OP02-092");
        impelDownStage.setName("Impel Down");
        impelDownStage.setCardType("Stage");
        impelDownStage.setColor("Purple");
        impelDownStage.setCost(1);
        impelDownStage.setAffiliations("Impel Down");
        impelDownStage.setEffect("Activate: Main You may trash 1 card from your hand and rest this Stage: Look at 3 cards from the top of your deck; reveal up to 1 {Impel Down} type card and add it to your hand. Then, place the rest at the bottom of your deck.");
        impelDownStage.setImagePath("/images/cards/OP02/OP02-092.png");
        cardRepository.save(impelDownStage);
        
        // Black Cards
        Card smokerLeader = new Card();
        smokerLeader.setCardNumber("OP02-093");
        smokerLeader.setName("Smoker");
        smokerLeader.setCardType("Leader");
        smokerLeader.setColor("Black");
        smokerLeader.setPower(5000);
        smokerLeader.setLife(5);
        smokerLeader.setAttribute("Special");
        smokerLeader.setAffiliations("Navy");
        smokerLeader.setEffect("DON!!x1 Activate: Main Once Per Turn Give up to 1 of your opponent's Characters -1 to their cost during this turn. Then, if there is a Character with a cost of 0 in play, this Leader gains +1000 Power during this turn.");
        smokerLeader.setImagePath("/images/cards/OP02/OP02-093.png");
        cardRepository.save(smokerLeader);
        
        Card isuka = new Card();
        isuka.setCardNumber("OP02-094");
        isuka.setName("Isuka");
        isuka.setCardType("Character");
        isuka.setColor("Black");
        isuka.setCost(3);
        isuka.setPower(4000);
        isuka.setCounter(1000);
        isuka.setAttribute("Slash");
        isuka.setAffiliations("Navy");
        isuka.setEffect("DON!!x1 Once Per Turn When this Character battles and K.O.s 1 of your opponent's Characters, set this Character as active.");
        isuka.setImagePath("/images/cards/OP02/OP02-094.png");
        cardRepository.save(isuka);

        Card onigumo = new Card();
        onigumo.setCardNumber("OP02-095");
        onigumo.setName("Onigumo");
        onigumo.setCardType("Character");
        onigumo.setColor("Black");
        onigumo.setCost(5);
        onigumo.setPower(6000);
        onigumo.setCounter(1000);
        onigumo.setAttribute("Slash");
        onigumo.setAffiliations("Navy");
        onigumo.setEffect("If there is a Character with a cost of 0 in play, this Character gains Banish (When a character deals damage, the target card is trashed without activating its Trigger.)");
        onigumo.setImagePath("/images/cards/OP02/OP02-095.png");
        cardRepository.save(onigumo);

        Card kuzanBlack = new Card();
        kuzanBlack.setCardNumber("OP02-096");
        kuzanBlack.setName("Kuzan");
        kuzanBlack.setCardType("Character");
        kuzanBlack.setColor("Black");
        kuzanBlack.setCost(4);
        kuzanBlack.setPower(5000);
        kuzanBlack.setAttribute("Special");
        kuzanBlack.setAffiliations("Navy");
        kuzanBlack.setEffect("On Play Draw 1 card.\\nWhen Attacking Give up to 1 of your opponent's Characters -4 to their cost during this turn.");
        kuzanBlack.setImagePath("/images/cards/OP02/OP02-096.png");
        cardRepository.save(kuzanBlack);

        Card comil = new Card();
        comil.setCardNumber("OP02-097");
        comil.setName("Comil");
        comil.setCardType("Character");
        comil.setColor("Black");
        comil.setCost(1);
        comil.setPower(3000);
        comil.setCounter(1000);
        comil.setAttribute("Slash");
        comil.setAffiliations("Navy");
        comil.setImagePath("/images/cards/OP02/OP02-097.png");
        cardRepository.save(comil);

        Card koby = new Card();
        koby.setCardNumber("OP02-098");
        koby.setName("Koby");
        koby.setCardType("Character");
        koby.setColor("Black");
        koby.setCost(3);
        koby.setPower(4000);
        koby.setCounter(1000);
        koby.setAttribute("Strike");
        koby.setAffiliations("Navy");
        koby.setEffect("On Play You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.");
        koby.setImagePath("/images/cards/OP02/OP02-098.png");
        cardRepository.save(koby);

        Card sakazuki = new Card();
        sakazuki.setCardNumber("OP02-099");
        sakazuki.setName("Sakazuki");
        sakazuki.setCardType("Character");
        sakazuki.setColor("Black");
        sakazuki.setCost(6);
        sakazuki.setPower(7000);
        sakazuki.setAttribute("Special");
        sakazuki.setAffiliations("Navy");
        sakazuki.setEffect("On Play You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.");
        sakazuki.setImagePath("/images/cards/OP02/OP02-099.png");
        cardRepository.save(sakazuki);

        Card djangoBlack = new Card();
        djangoBlack.setCardNumber("OP02-100");
        djangoBlack.setName("Django");
        djangoBlack.setCardType("Character");
        djangoBlack.setColor("Black");
        djangoBlack.setCost(2);
        djangoBlack.setPower(3000);
        djangoBlack.setCounter(1000);
        djangoBlack.setAttribute("Slash");
        djangoBlack.setAffiliations("Navy");
        djangoBlack.setEffect("If you have [Fullbody] in play, this Character cannot be K.O.'d by battle.");
        djangoBlack.setImagePath("/images/cards/OP02/OP02-100.png");
        cardRepository.save(djangoBlack);

        Card strawberry = new Card();
        strawberry.setCardNumber("OP02-101");
        strawberry.setName("Strawberry");
        strawberry.setCardType("Character");
        strawberry.setColor("Black");
        strawberry.setCost(4);
        strawberry.setPower(5000);
        strawberry.setAttribute("Slash");
        strawberry.setAffiliations("Navy");
        strawberry.setEffect("When Attacking If there is a Character with a cost of 0 in play, your opponent cannot activate a Blocker Character with a cost of 5 or less during this battle.");
        strawberry.setImagePath("/images/cards/OP02/OP02-101.png");
        cardRepository.save(strawberry);

        Card smoker = new Card();
        smoker.setCardNumber("OP02-102");
        smoker.setName("Smoker");
        smoker.setCardType("Character");
        smoker.setColor("Black");
        smoker.setCost(3);
        smoker.setPower(4000);
        smoker.setCounter(1000);
        smoker.setAttribute("Special");
        smoker.setAffiliations("Navy");
        smoker.setEffect("This Character cannot be K.O'ed by effects.\\nWhen Attacking If there is a Character with a cost of 0 in play, this Character gains +2000 power during this battle.");
        smoker.setImagePath("/images/cards/OP02/OP02-102.png");
        cardRepository.save(smoker);

        Card sengoku = new Card();
        sengoku.setCardNumber("OP02-103");
        sengoku.setName("Sengoku");
        sengoku.setCardType("Character");
        sengoku.setColor("Black");
        sengoku.setCost(2);
        sengoku.setPower(3000);
        sengoku.setCounter(2000);
        sengoku.setAttribute("Wisdom");
        sengoku.setAffiliations("Navy");
        sengoku.setEffect("DON!!x1 When Attacking Give up to 1 of your opponent's Characters -2 to thier cost during this turn.");
        sengoku.setImagePath("/images/cards/OP02/OP02-103.png");
        cardRepository.save(sengoku);

        Card sentomaru = new Card();
        sentomaru.setCardNumber("OP02-104");
        sentomaru.setName("Sentomaru");
        sentomaru.setCardType("Character");
        sentomaru.setColor("Black");
        sentomaru.setCost(2);
        sentomaru.setPower(3000);
        sentomaru.setCounter(1000);
        sentomaru.setAttribute("Slash");
        sentomaru.setAffiliations("Navy");
        sentomaru.setEffect("Trigger Play this card.");
        sentomaru.setImagePath("/images/cards/OP02/OP02-104.png");
        cardRepository.save(sentomaru);

        Card tashigi = new Card();
        tashigi.setCardNumber("OP02-105");
        tashigi.setName("Tashigi");
        tashigi.setCardType("Character");
        tashigi.setColor("Black");
        tashigi.setCost(3);
        tashigi.setPower(5000);
        tashigi.setCounter(1000);
        tashigi.setAttribute("Slash");
        tashigi.setAffiliations("Navy");
        tashigi.setEffect("DON!!x1 When Attacking Give up to 1 of your opponent's Characters -3 to their cost during this turn.");
        tashigi.setImagePath("/images/cards/OP02/OP02-105.png");
        cardRepository.save(tashigi);

        Card tsuru = new Card();
        tsuru.setCardNumber("OP02-106");
        tsuru.setName("Tsuru");
        tsuru.setCardType("Character");
        tsuru.setColor("Black");
        tsuru.setCost(1);
        tsuru.setPower(0);
        tsuru.setCounter(2000);
        tsuru.setAttribute("Wisdom");
        tsuru.setAffiliations("Navy");
        tsuru.setEffect("On Play Give up to 1 of your opponent's Characters -2 to their cost during this turn.");
        tsuru.setImagePath("/images/cards/OP02/OP02-106.png");
        cardRepository.save(tsuru);

        Card doberman = new Card();
        doberman.setCardNumber("OP02-107");
        doberman.setName("Doberman");
        doberman.setCardType("Character");
        doberman.setColor("Black");
        doberman.setCost(2);
        doberman.setPower(4000);
        doberman.setCounter(1000);
        doberman.setAttribute("Strike");
        doberman.setAffiliations("Navy");
        doberman.setImagePath("/images/cards/OP02/OP02-107.png");
        cardRepository.save(doberman);

        Card donquixoteRosinante = new Card();
        donquixoteRosinante.setCardNumber("OP02-108");
        donquixoteRosinante.setName("Donquixote Rosinante");
        donquixoteRosinante.setCardType("Character");
        donquixoteRosinante.setColor("Black");
        donquixoteRosinante.setCost(2);
        donquixoteRosinante.setPower(2000);
        donquixoteRosinante.setCounter(1000);
        donquixoteRosinante.setAttribute("Special");
        donquixoteRosinante.setAffiliations("Navy/Donquixote Pirates");
        donquixoteRosinante.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        donquixoteRosinante.setImagePath("/images/cards/OP02/OP02-108.png");
        cardRepository.save(donquixoteRosinante);

        Card jaguarDSaul = new Card();
        jaguarDSaul.setCardNumber("OP02-109");
        jaguarDSaul.setName("Jaguar D. Saul");
        jaguarDSaul.setCardType("Character");
        jaguarDSaul.setColor("Black");
        jaguarDSaul.setCost(4);
        jaguarDSaul.setPower(6000);
        jaguarDSaul.setCounter(1000);
        jaguarDSaul.setAttribute("Strike");
        jaguarDSaul.setAffiliations("Giant/Navy");
        jaguarDSaul.setImagePath("/images/cards/OP02/OP02-109.png");
        cardRepository.save(jaguarDSaul);

        Card hina = new Card();
        hina.setCardNumber("OP02-110");
        hina.setName("Hina");
        hina.setCardType("Character");
        hina.setColor("Black");
        hina.setCost(5);
        hina.setPower(6000);
        hina.setCounter(1000);
        hina.setAttribute("Special");
        hina.setAffiliations("Navy");
        hina.setEffect("Blocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\\nOn Block Choose up to 1 of your opponent's Characters with a cost of 6 or less. The chosen Character cannot attack during this turn.");
        hina.setImagePath("/images/cards/OP02/OP02-110.png");
        cardRepository.save(hina);

        Card fullbody = new Card();
        fullbody.setCardNumber("OP02-111");
        fullbody.setName("Fullbody");
        fullbody.setCardType("Character");
        fullbody.setColor("Black");
        fullbody.setCost(2);
        fullbody.setPower(3000);
        fullbody.setCounter(1000);
        fullbody.setAttribute("Strike");
        fullbody.setAffiliations("Navy");
        fullbody.setEffect("When Attacking If you have [Django] in play, this Character gains +3000 Power during this battle.");
        fullbody.setImagePath("/images/cards/OP02/OP02-111.png");
        cardRepository.save(fullbody);

        Card bellmere = new Card();
        bellmere.setCardNumber("OP02-112");
        bellmere.setName("Bell-mère");
        bellmere.setCardType("Character");
        bellmere.setColor("Black");
        bellmere.setCost(1);
        bellmere.setPower(1000);
        bellmere.setCounter(1000);
        bellmere.setAttribute("Ranged");
        bellmere.setAffiliations("Navy");
        bellmere.setEffect("Activate: Main You may rest this Character: Give up to 1 of your opponent's Characters -1 to their cost during this turn. Then, your Leader or up to 1 of your Characters gains +1000 Power during this turn.");
        bellmere.setImagePath("/images/cards/OP02/OP02-112.png");
        cardRepository.save(bellmere);

        Card helmeppoBlack = new Card();
        helmeppoBlack.setCardNumber("OP02-113");
        helmeppoBlack.setName("Helmeppo");
        helmeppoBlack.setCardType("Character");
        helmeppoBlack.setColor("Black");
        helmeppoBlack.setCost(3);
        helmeppoBlack.setPower(5000);
        helmeppoBlack.setCounter(1000);
        helmeppoBlack.setAttribute("Slash");
        helmeppoBlack.setAffiliations("Navy");
        helmeppoBlack.setEffect("When Attacking Give up to 1 of your opponent's Characters -2 to their cost. Then, if there's a Character with a cost of 0 in play, this Character gains +2000 Power during this battle.\\nTrigger Play this card.");
        helmeppoBlack.setImagePath("/images/cards/OP02/OP02-113.png");
        cardRepository.save(helmeppoBlack);

        Card borsalino = new Card();
        borsalino.setCardNumber("OP02-114");
        borsalino.setName("Borsalino");
        borsalino.setCardType("Character");
        borsalino.setColor("Black");
        borsalino.setCost(4);
        borsalino.setPower(5000);
        borsalino.setCounter(1000);
        borsalino.setAttribute("Special");
        borsalino.setAffiliations("Navy");
        borsalino.setEffect("Opponent's Turn This Character gains +1000 Power and cannot be K.O.ed by effects.\\nBlocker (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)");
        borsalino.setImagePath("/images/cards/OP02/OP02-114.png");
        cardRepository.save(borsalino);

        Card monkeyDGarpBlack = new Card();
        monkeyDGarpBlack.setCardNumber("OP02-115");
        monkeyDGarpBlack.setName("Monkey. D. Garp");
        monkeyDGarpBlack.setCardType("Character");
        monkeyDGarpBlack.setColor("Black");
        monkeyDGarpBlack.setCost(2);
        monkeyDGarpBlack.setPower(3000);
        monkeyDGarpBlack.setCounter(2000);
        monkeyDGarpBlack.setAttribute("Strike");
        monkeyDGarpBlack.setAffiliations("Navy");
        monkeyDGarpBlack.setEffect("DON!!x2 When Attacking K.O. up to 1 of your opponent's Characters with a cost of 0.");
        monkeyDGarpBlack.setImagePath("/images/cards/OP02/OP02-115.png");
        cardRepository.save(monkeyDGarpBlack);

        Card yamakaji = new Card();
        yamakaji.setCardNumber("OP02-116");
        yamakaji.setName("Yamakaji");
        yamakaji.setCardType("Character");
        yamakaji.setColor("Black");
        yamakaji.setCost(3);
        yamakaji.setPower(5000);
        yamakaji.setCounter(1000);
        yamakaji.setAttribute("Slash");
        yamakaji.setAffiliations("Navy");
        yamakaji.setImagePath("/images/cards/OP02/OP02-116.png");
        cardRepository.save(yamakaji);
        
        // Black Events
        Card iceAge = new Card();
        iceAge.setCardNumber("OP02-117");
        iceAge.setName("Ice Age");
        iceAge.setCardType("Event");
        iceAge.setColor("Black");
        iceAge.setCost(1);
        iceAge.setAffiliations("Navy");
        iceAge.setEffect("Main Give up to 1 of your opponent's Characters -5 to their cost during this turn.\\nTrigger K.O. up to 1 of your opponent's Characters with a cost of 3 or less.");
        iceAge.setImagePath("/images/cards/OP02/OP02-117.png");
        cardRepository.save(iceAge);

        Card yasakaniSacredJewel = new Card();
        yasakaniSacredJewel.setCardNumber("OP02-118");
        yasakaniSacredJewel.setName("Yasakani Sacred Jewel");
        yasakaniSacredJewel.setCardType("Event");
        yasakaniSacredJewel.setColor("Black");
        yasakaniSacredJewel.setCost(1);
        yasakaniSacredJewel.setAffiliations("Navy");
        yasakaniSacredJewel.setEffect("Counter You may trash 1 card from your hand: Choose up to 1 of your Characters, that Character cannot be K.O'ed during this battle.\\nTrigger K.O. up to 1 of your opponent's Stage cards with a cost of 3 or less.");
        yasakaniSacredJewel.setImagePath("/images/cards/OP02/OP02-118.png");
        cardRepository.save(yasakaniSacredJewel);

        Card meteorVolcano = new Card();
        meteorVolcano.setCardNumber("OP02-119");
        meteorVolcano.setName("Meteor Volcano");
        meteorVolcano.setCardType("Event");
        meteorVolcano.setColor("Black");
        meteorVolcano.setCost(2);
        meteorVolcano.setAffiliations("Navy");
        meteorVolcano.setEffect("Main K.O. up to 1 of your opponent's Characters with a cost of 1 or less.\\nTrigger Draw 2 cards and trash 1 card from your hand.");
        meteorVolcano.setImagePath("/images/cards/OP02/OP02-119.png");
        cardRepository.save(meteorVolcano);
        
        // Secret Rares
        Card utaSec = new Card();
        utaSec.setCardNumber("OP02-120");
        utaSec.setName("Uta");
        utaSec.setCardType("Character");
        utaSec.setColor("Purple"); // Assuming Purple from border
        utaSec.setCost(8);
        utaSec.setPower(8000);
        utaSec.setAttribute("Special");
        utaSec.setAffiliations("FILM");
        utaSec.setEffect("On Play DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck): Your Leader and all your Characters gain +1000 Power until the start of your next turn.");
        utaSec.setImagePath("/images/cards/OP02/OP02-120.png");
        cardRepository.save(utaSec);

        Card kuzanSec = new Card();
        kuzanSec.setCardNumber("OP02-121");
        kuzanSec.setName("Kuzan");
        kuzanSec.setCardType("Character");
        kuzanSec.setColor("Black"); // Assuming Black from border
        kuzanSec.setCost(10);
        kuzanSec.setPower(10000);
        kuzanSec.setAttribute("Special");
        kuzanSec.setAffiliations("Former Navy");
        kuzanSec.setEffect("Your Turn All of your opponent's Characters get -5 to their cost.\\nOn Play K.O. up to 1 of your opponent's Characters with a cost of 0.");
        kuzanSec.setImagePath("/images/cards/OP02/OP02-121.png");
        cardRepository.save(kuzanSec);

        System.out.println("Finished initializing OP02 cards");
    }
} 